import Head from "next/head";
import Carousel from "../components/Carousel";
import Video from "../components/Video";
import Gallery from "../components/Gallery";
import Valores from "../components/Valores";
import SimpleMap from "../components/SimpleMap";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Flavia Machado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo-1.png" />
      </Head>
      <Carousel />
      <Video />
      <Gallery />
      <Valores />
      <SimpleMap />
    </div>
  );
}
